name: string_upper_lower_package
description: This package will make your text strings smaller if they are big and bigger if they are small.
version: 1.0.0
repository: https://github.com/asadbekxomidov/string_upper_lower_package

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
